apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 8090   # Exposing ArgoCD at port 8090 externally
  type: LoadBalancer
